[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter @pomogator/shared build",
  "pnpm --filter @pomogator/redis build",
  "pnpm --filter @pomogator/prisma generate", 
  "pnpm --filter @pomogator/bot build"
]

[start]
cmd = "pnpm start"
